---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Declare relevant playbook variables
  # Important force parsing with Jinja2
  # NOTE Remember to update README file

  ansible.builtin.set_fact:

    sslca_authority: >-
      {{ sslca_authority | default(omit) }}
    sslca_certificate: >-
      {{ sslca_certificate | default(omit) }}

    sslca_persist: >-
      {{ sslca_persist | default(omit) }}
    sslca_persist_rootkeys: >-
      {{ sslca_persist_rootkeys | default(omit) }}
    sslca_persist_rootfiles: >-
      {{ sslca_persist_rootfiles | default(omit) }}
    sslca_persist_certkeys: >-
      {{ sslca_persist_certkeys | default(omit) }}
    sslca_persist_certfiles: >-
      {{ sslca_persist_certfiles | default(omit) }}

    sslca_defaults: >-
      {{ sslca_defaults | default(omit) }}
    sslca_defaults_company: >-
      {{ sslca_defaults_company | default(omit) }}
    sslca_defaults_department: >-
      {{ sslca_defaults_department | default(omit) }}
    sslca_defaults_country: >-
      {{ sslca_defaults_country | default(omit) }}
    sslca_defaults_website: >-
      {{ sslca_defaults_website | default(omit) }}

    sslca_openssl: >-
      {{ sslca_openssl | default(omit) }}

  tags: always






- name: Validate role variables using Pydantic

  enasisnetwork.certauth.sslca.params:
    prefix: sslca_

  register: pbvalidate

  tags: always






- name: Declare relevant playbook variables
  # Required to retain child null value

  ansible.builtin.set_fact:

    sslca_authority: >-
      {{ pbvalidate.params.authority }}
    sslca_certificate: >-
      {{ pbvalidate.params.certificate }}
    sslca_persist: >-
      {{ pbvalidate.params.persist }}
    sslca_defaults: >-
      {{ pbvalidate.params.defaults }}
    sslca_openssl: >-
      {{ pbvalidate.params.openssl }}

  tags: always
